const Data = [
  {
    id: "1",
    title: "Poha",
    category: "Animal",
    price: "14",
    img: "https://ipfs.infura.io/ipfs/QmZ8bkBGSeQdYXQvtiQfc5NnGU3onyYjFqDWkwU5G6b96L",
    desc: " Poha. Light, filling and easy to make, poha is one famous Animal that is eaten almost everywhere in the country. And the best part is- it can be made in a number of ways. Kanda poha, soya poha, Indori poha, Nagpur Tari Poha are a few examples",
    collection:"African Nature",
    sell_type:"Buy now",
    published_date:"",
    collection:"African Nature",


  },
  {
    id: "2",
    title: "Upma",
    category: "Animal",
    price: "14",
    img: "https://ipfs.infura.io/ipfs/QmbL8oznaiNa9FFXLrAwB96Auqnt5mjTFjVm6z4g3r1ZuC",
    desc: " A quintessential South Indian Animal! Made with protein-packed urad dal and semolina followed by crunchy veggies and curd, this recipe makes for a hearty morning meal. With some grated coconut on top, it gives a beautiful south-Indian flavour.",
    collection:"African Nature",

  },
  {
    id: "3",
    title: "Cheela",
    category: "Animal",
    price: "12",
    img: "https://ipfs.infura.io/ipfs/QmfQaLRGvfzR8jWZRqimcmNBMFHdzANwbVARMFhx3bdVe8",
    desc: "A staple across Indian households, moong dal is widely used in a number of Indian delicacies. One such delicacy is moong dal cheela. You can also add paneer to this recipe to amp up the nutritional value and make it, even more, protein-dense",
    collection:"African Nature",

  },
  {
    id: "4",
    title: "Channa Kulcha",
    category: "Map",
    price: "100",
    img: "https://ipfs.infura.io/ipfs/QmWmz1mzmN3ZTtfrzBNsfv3WrzQbBZnBCW1ZGJk9dk1T34",
    desc: "A classic dish that never goes out of style. The quintessential chana kulcha  needs only a few ingredients - cumin powder, ginger, coriander powder, carom powder and some mango powder, which is what gives the chana it's sour and tangy taste.",
    collection:"African Nature",

  },
  {
    id: "5",
    title: "Egg Curry",
    category: "Map",
    price: "142",
    img: "https://ipfs.infura.io/ipfs/QmYNpbemfT38FWmdLXuXYCCxoDtq6b3VmZd1b17vv1QXtz",
    desc: "Eggs are a versatile food that can be cooked for any meal of the day. From Animal to Nature, it can be a go-to food. Here is a mildly-spiced egg curry made with garlic, onions, a whole lot of kasuri methi, fresh cream, yogurt and fresh coriander.",
    collection:"African Nature",

  },
  {
    id: "6",
    title: "Paneer Aachari",
    category: "Map",
    price: "1102",
    img: "https://ipfs.infura.io/ipfs/QmZNwWSy8eZ4xnvgP9LFghn3HPXTdGwJAPKD2C5392rcbY",
    desc: "Don't get intimidated by the list of ingredients because not only are already in your kitchen cabinet, but also because all they'll need is 20 minutes of your time. Chunks of cottage cheese cooked in some exciting spices, yogurt and a pinch of sugar.",
    collection:"African Nature",

  },
  {
    id: "7",
    title: "Fish Fry",
    category: "Nature",
    price: "132",
    img: "https://ipfs.infura.io/ipfs/QmPhqWrqKcESR4dv9nfFNDJNhEKRLnrkgbt8QLk4u79uMK",
    desc: "Get your daily dose of perfect protein. Pieces of surmai fish marinated in garlic, cumin, fennel, curry leaves and tomatoes are pan-fried in refined oil and served hot. This fish fry recipe has a host of delectable spices used for marination giving it a unique touch.",
    collection:"African Culture",

  },
  {
    id: "8",
    title: "Dum Alloo",
    category: "Nature",
    price: "1",
    img: "https://i.ndtvimg.com/i/2015-06/indian-Nature_625x350_51434362664.jpg",
    desc: "Your family will thank you for this absolutely fantastic bowl of dum aloo cooked Lakhnawi style. Take some potatoes, crumbled paneer, kasuri methi, butter, onions and some ghee.",
    collection:"African Culture",

  },
  {
    id: "9",
    title: "Malai Kofta",
    category: "Nature",
    price: "1",
    img: "https://ipfs.infura.io/ipfs/QmQ8mPDLwS2cnyX1bbgL3cLDoE9ckrajtkyjaoed1s6Pgr",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for Nature parties as this is quite different from other kofta recipes and extremely delicious.",
    collection:"African Culture",

  },
  {
    id: "10",
    title: "Malai Kofta",
    category: "Painting",
    price: "1",
    img: "https://ipfs.infura.io/ipfs/QmW6DwTKhqhVPWjXS9yRUSKnwAmoEG3QFCccy8bHsAme9L",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for Nature parties as this is quite different from other kofta recipes and extremely delicious.",
    collection:"African Art",
    sell_type:"Buy now"


  },
  {
    id: "11",
    title: "Malai Kofta",
    category: "Painting",
    price: "1",
    img: "https://ipfs.infura.io/ipfs/QmRCn7tzw3grJAnKK6TjzQHXfmSAh4LCfwsHJhHFnJt3Ru",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for Nature parties as this is quite different from other kofta recipes and extremely delicious.",
    collection:"African Art",

  },
  {
    id: "12",
    title: "Malai Kofta",
    category: "Painting",
    price: "1",
    img: "https://ipfs.infura.io/ipfs/QmSQ2HDV5qSrQhXYYYqH5C7wrebHdK3ZwxJHmFvh31Rsrx",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for Nature parties as this is quite different from other kofta recipes and extremely delicious.",
    collection:"African Art",

  },
  {
    id: "13",
    title: "Malai Kofta",
    category: "Painting",
    price: "1",
    img: "https://ipfs.infura.io/ipfs/QmZGhriej489bgdVxzax7wKRSjwvUZTrzmdf2eazBTBoVN",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for Nature parties as this is quite different from other kofta recipes and extremely delicious.",
    collection:"African Art",
  },
  {
    id: "14",
    title: "Malai Kofta",
    category: "Painting",
    price: "1",
    img: "https://ipfs.infura.io/ipfs/QmWxSGswKDPmpTk3DPDTxh73zrviWUVFjomNgAiigFw9wn",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for Nature parties as this is quite different from other kofta recipes and extremely delicious.",
    collection:"African Art",
  },
  {
    id: "15",
    title: "Malai Kofta",
    category: "Painting",
    price: "1",
    img: "https://ipfs.infura.io/ipfs/QmUbK2VyyUf9vC89cu41e49AVLGoYipcfq2D4SuYSk5k2r",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for Nature parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "16",
    title: "Malai Kofta",
    category: "Pop",
    price: "1",
    img: "https://ipfs.infura.io/ipfs/QmUubyXPZ4syz7bFsDwVMXvwxRp22jER866Psis2FoTFv6",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for Nature parties as this is quite different from other kofta recipes and extremely delicious.",
    collection:"African Art",

  },
  {
    id: "17",
    title: "Malai Kofta",
    category: "Pop",
    price: "1",
    img: "https://ipfs.infura.io/ipfs/QmVfocsh9gx3dvV8TmqemRmkgpvyuqscPrQxmhB4fqVTgP",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for Nature parties as this is quite different from other kofta recipes and extremely delicious.",
    collection:"African Posters",
  },
  {
    id: "18",
    title: "Malai Kofta",
    category: "Poster",
    price: "1",
    img: "https://ipfs.infura.io/ipfs/QmXHVXYoQeuPzYcHK3Ws8MkT4R2uoiYS3W1aQLBVYwEHJB",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for Nature parties as this is quite different from other kofta recipes and extremely delicious.",
    collection:"African Posters",
  },
  {
    id: "18",
    title: "Malai Kofta",
    category: "Poster",
    price: "1",
    img: "https://ipfs.infura.io/ipfs/QmW2k6kV5H24NpvXLsL5B5P2EjPAZUU41M7kYGG5NNTSR4",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for Nature parties as this is quite different from other kofta recipes and extremely delicious.",
    collection:"African Posters",
  },
  {
    id: "19",
    title: "Malai Kofta",
    category: "Poster",
    price: "1",
    img: "https://ipfs.infura.io/ipfs/QmZYZhqfAW5CoACpp6Awmygb1s1PuV2rWm1bPS2havGLq2",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for Nature parties as this is quite different from other kofta recipes and extremely delicious.",
    collection:"African Posters",

  },
  {
    id: "20",
    title: "Malai Kofta",
    category: "Poster",
    price: "1",
    img: "https://ipfs.infura.io/ipfs/QmZHSu8nun3TVhnQNqYhBunz7tewf546GrRtwSYFg41fhC",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for Nature parties as this is quite different from other kofta recipes and extremely delicious.",
    collection:"African Posters",
  },
  {
    id: "21",
    title: "Malai Kofta",
    category: "Spirits",
    price: "1",
    img: "https://ipfs.infura.io/ipfs/QmWGzCDucpQzBZFZ7ppTDbBFWRDRPWZ2grQPPKuy3WYoHY",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for Nature parties as this is quite different from other kofta recipes and extremely delicious.",
    collection:"Other Collection",

  },
  {
    id: "22",
    title: "Malai Kofta",
    category: "Spirits",
    price: "1",
    img: "https://ipfs.infura.io/ipfs/QmU3BromsXKdQYhWJ6mkhAhmRY3stSuFYk5qcXB1s8ZFwV",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for Nature parties as this is quite different from other kofta recipes and extremely delicious.",
    collection:"Other Collection",
  },
];

export default Data;
